/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface BenchmarkResults {
  benchmark_name: string;
  created_at: Generated<Timestamp>;
  id: string;
  milestone_id: string;
  normalized_ratio: Numeric;
  raw_metrics: Json;
  reference_version: string;
  submission_id: string;
  user_id: string;
}

export interface CodeSnapshots {
  code: string;
  created_at: Generated<Timestamp>;
  id: string;
  milestone_id: string;
  session_id: string;
  user_id: string;
}

export interface DataExports {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  error_message: string | null;
  export_data: Json | null;
  id: string;
  status: Generated<string>;
  user_id: string;
}

export interface MilestoneCompletionMetrics {
  completed_users: Int8 | null;
  first_completion_at: Timestamp | null;
  latest_completion_at: Timestamp | null;
  milestone_id: string | null;
  milestone_position: number | null;
  milestone_slug: string | null;
  milestone_title: string | null;
  track_name: string | null;
  track_slug: string | null;
}

export interface MilestoneDropoutAnalysis {
  completed: boolean | null;
  experience_level: string | null;
  first_session_at: Timestamp | null;
  last_activity_at: Timestamp | null;
  milestone_id: string | null;
  milestone_position: number | null;
  milestone_slug: string | null;
  milestone_title: string | null;
  session_count: Int8 | null;
  submission_count: Int8 | null;
  user_id: string | null;
  user_role: string | null;
}

export interface Milestones {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: string;
  position: number;
  slug: string;
  title: string;
  track_id: string;
  updated_at: Generated<Timestamp>;
}

export interface MilestoneTimeToCompletion {
  completed_at: Timestamp | null;
  experience_level: string | null;
  first_session_at: Timestamp | null;
  milestone_id: string | null;
  milestone_position: number | null;
  milestone_slug: string | null;
  milestone_title: string | null;
  time_to_completion_seconds: Numeric | null;
  total_sessions: Int8 | null;
  total_submissions: Int8 | null;
  user_id: string | null;
  user_role: string | null;
}

export interface PlatformSignupMetrics {
  learner_count: Int8 | null;
  onboarding_completed_count: Int8 | null;
  signup_count: Int8 | null;
  signup_date: Timestamp | null;
  skill_floor_passed_count: Int8 | null;
}

export interface Sessions {
  ended_at: Timestamp | null;
  id: string;
  is_active: Generated<boolean>;
  milestone_id: string;
  started_at: Generated<Timestamp>;
  user_id: string;
}

export interface SessionSummaries {
  created_at: Generated<Timestamp>;
  id: string;
  milestone_id: string;
  session_id: string;
  summary_text: string;
  user_id: string;
}

export interface Submissions {
  code: string;
  created_at: Generated<Timestamp>;
  criteria_results: Json | null;
  error_message: string | null;
  execution_result: Json | null;
  id: string;
  milestone_id: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Tracks {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: string;
  name: string;
  slug: string;
  updated_at: Generated<Timestamp>;
}

export interface TutorConversationLog {
  content: string | null;
  created_at: Timestamp | null;
  message_id: string | null;
  message_role: string | null;
  milestone_id: string | null;
  milestone_position: number | null;
  milestone_slug: string | null;
  milestone_title: string | null;
  model: string | null;
  session_id: string | null;
  user_display_name: string | null;
  user_email: string | null;
  user_experience_level: string | null;
  user_id: string | null;
  user_primary_language: string | null;
  user_role: string | null;
}

export interface TutorMessages {
  content: string;
  created_at: Generated<Timestamp>;
  id: string;
  model: string | null;
  role: string;
  session_id: string;
  user_id: string;
}

export interface TutorSessionSummary {
  assistant_messages: Int8 | null;
  duration_seconds: Numeric | null;
  experience_level: string | null;
  first_message_at: Timestamp | null;
  haiku_messages: Int8 | null;
  last_message_at: Timestamp | null;
  milestone_id: string | null;
  milestone_slug: string | null;
  milestone_title: string | null;
  primary_language: string | null;
  session_id: string | null;
  sonnet_messages: Int8 | null;
  total_messages: Int8 | null;
  user_id: string | null;
  user_messages: Int8 | null;
  user_role: string | null;
}

export interface UserMilestones {
  completed_at: Generated<Timestamp>;
  completing_submission_id: string | null;
  created_at: Generated<Timestamp>;
  id: string;
  milestone_id: string;
  user_id: string;
}

export interface UserResourceConsumption {
  email: string | null;
  failed_submissions: Int8 | null;
  haiku_messages: Int8 | null;
  milestones_completed: Int8 | null;
  signup_date: Timestamp | null;
  sonnet_messages: Int8 | null;
  successful_submissions: Int8 | null;
  total_benchmark_runs: Int8 | null;
  total_code_snapshots: Int8 | null;
  total_sessions: Int8 | null;
  total_submissions: Int8 | null;
  total_tutor_messages: Int8 | null;
  user_id: string | null;
  user_role: string | null;
}

export interface UserRetentionDaily {
  activity_date: Timestamp | null;
  experience_level: string | null;
  milestones_touched: Int8 | null;
  session_count: Int8 | null;
  signup_date: Timestamp | null;
  user_id: string | null;
  user_role: string | null;
}

export interface Users {
  created_at: Generated<Timestamp>;
  display_name: string | null;
  email: string;
  experience_level: string | null;
  id: string;
  onboarding_completed_at: Timestamp | null;
  primary_language: string | null;
  role: string | null;
  skill_floor_completed_at: Timestamp | null;
  skill_floor_passed: boolean | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  benchmark_results: BenchmarkResults;
  code_snapshots: CodeSnapshots;
  data_exports: DataExports;
  milestone_completion_metrics: MilestoneCompletionMetrics;
  milestone_dropout_analysis: MilestoneDropoutAnalysis;
  milestone_time_to_completion: MilestoneTimeToCompletion;
  milestones: Milestones;
  platform_signup_metrics: PlatformSignupMetrics;
  session_summaries: SessionSummaries;
  sessions: Sessions;
  submissions: Submissions;
  tracks: Tracks;
  tutor_conversation_log: TutorConversationLog;
  tutor_messages: TutorMessages;
  tutor_session_summary: TutorSessionSummary;
  user_milestones: UserMilestones;
  user_resource_consumption: UserResourceConsumption;
  user_retention_daily: UserRetentionDaily;
  users: Users;
}
